#! /bin/bash
#script to id filesystem type for raw disk images using disktype, mount accordingly (currently only hfs and vfat),
#run hashdeep to create dfxml and .csv reports, and 
#use rsync to extract files to /Extracted folder
#assumes /mnt/diskid exists
#assumes $DIR/Extracted exists
#assumes disktype, hashdeep are installed

### TO DO: write in directory structure

#make cwd a variable
CWD=$(pwd)
echo $CWD
LOGFILE=extract.log

#iterate for every .img file (warning: recursive, limit depth on find with -maxdepth)
##for FILE in *.img
for FILE in $(find . -name '*.img');
do
#make variable SYSTEM based on a grep of disktype's output
	SYSTEM=$(disktype "$FILE" | grep "file system")
	printf "File: %s , System: %s\n" "$FILE" "$SYSTEM" >> $LOGFILE
#make variable DIR based on directory containing $FILE
	DIR=$(dirname $(realpath $FILE))
#if SYSTEM contains FAT
	if [[ $SYSTEM == "FAT"* ]]
	then
#mounts the image in order to run md5deep, note the mount command 
		sudo mount -t vfat -o loop,ro,noexec $FILE /mnt/diskid/
#just verify it mounted
		echo $?
#cd to mount directory,
#IMPORTANT NOTE:::: assumes /mnt/diskid exists
		cd /mnt/diskid
#use hashdeep to create .csv for use by archivists and appraisers
		hashdeep -r -l -c md5 ./* > "$DIR""/manifest.csv" 
		hashdeep -r -l -d -c md5 ./* > "$DIR""/dfxml.xml"
#rsync -a all files to $/DIR/Extracted/
#IMPORTANT NOTE:::: assumes $DIR/Extracted/ exists, can create with something like mkdir $DIR/Extracted/
		rsync -av ./ "$DIR""/Extracted/"
#cd back to cwd and unmount
		cd "$CWD"
		sudo umount /mnt/diskid		
#if SYSTEM contains HFS
	elif [[ $SYSTEM == "HFS"* ]]
	then 
#mount the image according to forensicwiki mounting suggestions
		sudo mount -t hfs -o loop,ro,noexec $FILE /mnt/diskid/
#just verify it mounted
		echo $?
#cd to mount directory
		cd /mnt/diskid
#use hashdeep to create DFXML and .csv files
		hashdeep -r -l -c md5 ./* > "$DIR""/manifest.csv"
		hashdeep -r -l -d -c md5 ./* > "$DIR""/dfxml.xml"
#rsync -a all files to $DIR/Extracted/
#add -n flag to test dry run
		rsync -av ./ "$DIR""/Extracted/" 
#cd back to cwd and unmount
		cd "$CWD"
		sudo umount /mnt/diskid	
	fi
done
		

